#
# Hyper Parameter
#

#
train:
  ed: 400
  lr: 0.01
  dr: 1.0
  ls: 0.01
#
model:
    tg: 1.0
    fr: 32
#
net:
  d1: 0.2
  d2: 0.4
  d3: 0.6
#
loss:
  margin: 0.1
#
reg:
  l1: 0.0
  l2: 0.0
  re: 0.0
  rt: 0.0
#
norm:
  alpha: 1e-12
