#
# Run
#

#
hw:
  device: "cpu"
  cuda: True
#
log:
  eval_step: 10
  test_step: 100
#
out:
  save: False
  dir: None
#
mode:
  aug: 0
  reg: 0
  mod: 0
#
exp:
  epochs: 1000
  batch: 512
#
trainer:
  type: "ova"
  params: []
#
data:
  kg: "icews14"
